//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquareList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCliente
    {
        public int codCli { get; set; }
        public string nomeCli { get; set; }
        public string sobrenomeCli { get; set; }
        public string telCli { get; set; }
        public string cpfCli { get; set; }
        public string sexCli { get; set; }
        public string endCli { get; set; }
        public string complCli { get; set; }
        public string emailCli { get; set; }
        public string senhaCli { get; set; }
    }
}
